# Generated by Django 6.0.5 on 2026-05-07 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('network_downtime', 'Network Downtime'), ('high_transaction_fees', 'High Transaction Fees'), ('slow_internet', 'Slow Internet'), ('support_delays', 'Customer Support Delays'), ('billing_errors', 'Billing Errors')], max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('pending', 'Pending')], default='open', max_length=20)),
                ('sentiment_score', models.FloatField()),
                ('resolution_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='customers.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='providers.service')),
            ],
        ),
    ]
