# Generated by Django 6.0.5 on 2026-05-07 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('nairobi', 'Nairobi'), ('coast', 'Coast'), ('western', 'Western'), ('rift_valley', 'Rift Valley'), ('north_eastern', 'North Eastern'), ('central', 'Central'), ('eastern', 'Eastern'), ('nyanza', 'Nyanza')], max_length=50)),
                ('subscription_type', models.CharField(choices=[('prepaid', 'Prepaid'), ('postpaid', 'Postpaid'), ('enterprise', 'Enterprise')], max_length=20)),
                ('signup_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_activity', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='providers.provider')),
            ],
        ),
        migrations.CreateModel(
            name='SatisfactionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('nps_response', models.IntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_scores', to='customers.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_scores', to='providers.service')),
            ],
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('data_usage_gb', models.FloatField(default=0.0)),
                ('call_minutes', models.IntegerField(default=0)),
                ('transaction_count', models.IntegerField(default=0)),
                ('monthly_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='customers.customer')),
            ],
            options={
                'unique_together': {('customer', 'month')},
            },
        ),
    ]
