# Generated by Django 6.0.5 on 2026-05-07 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(choices=[('safaricom', 'Safaricom'), ('airtel', 'Airtel Kenya'), ('telkom', 'Telkom Kenya')], max_length=50, unique=True)),
                ('founded', models.IntegerField(default=2000)),
                ('hq_location', models.CharField(default='Nairobi', max_length=100)),
                ('market_share_percent', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('data_bundles', 'Data Bundles'), ('voice', 'Voice'), ('sms', 'SMS'), ('customer_support', 'Customer Support')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('launched_at', models.DateField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='providers.provider')),
            ],
            options={
                'unique_together': {('provider', 'service_type')},
            },
        ),
    ]
